version: "3"
services:
    api:
        image: api
        depends_on:
            - mysql
        ports:
            - "88:80"
    mysql:
        image: mysql
        ports:
            - "3306:3306"
    nginx:
        image: nginx
        volumes:
            - /home/pi/docker/webserver/normal:/website/normal
            - /home/pi/docker/webserver/config/:/etc/nginx/sites-available
        ports:
            - "80:80"

volumes:
    normal:
    config:
